services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data    

  backend:
    build: ./backend
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend/public:/app/public

  frontend:
    build: ./atakent-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./atakent-frontend/.env
    depends_on:
      - backend

  migrations:
    build: ./backend
    command: npm run migration:run
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pg_data: