services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data    

  backend:
    build: ./backend
    command: sh -c "npm run migration:run && npm run seed:admin"
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
         condition: service_healthy

    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/public:/app/public  

  frontend:
    build: ./atakent-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./atakent-frontend/.env
    depends_on:
      - backend

  migrations:
    build: ./backend
    command: npm run migration:run
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  pg_data: